# Go Decoder CI
name: Go Decoder CI

on:
  push:
    paths:
      - decoder/go/**
  pull_request:
    branches:
      - main
      - dev
      - feature/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - 1.17.x
#          - 1.18.x
        os:
          - ubuntu-latest
          - windows-latest
    defaults:
      run:
        working-directory: ./decoder/go

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Prepare environment
        run: |
          go install golang.org/x/lint/golint@latest
          go mod vendor
          
      - name: Run build
        run: go build -x

      - name: Run vet & lint
        run: |
          go vet .
          golint .
          
      - name: Run tests
        run: go test ./...

      - name: Install GoSec
        shell: bash
        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/v2.9.1/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.9.1

      - name: Run security scan
        run: gosec ./...