# Go Encoder CI
name: Go Encoder CI

on:
  push:
    paths:
      - encoder/go/**
  pull_request:
    branches:
      - main
      - dev
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./encoder/go

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Prepare environment
        run: |
          go install golang.org/x/lint/golint@latest
          go mod vendor
          
      - name: Run build
        run: go build -x

      - name: Run vet & lint
        run: |
          go vet .
          golint .
          
      - name: Run tests
        run: go test ./...

      - name: Install GoSec
        shell: bash
        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/v2.11.0/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.11.0

      - name: Run security scan
        run: gosec ./...